import styles from "../styles/pages/Home.module.scss";

//import components
import Head from "next/head";
import Footer from "../components/Footer";
import Header from "../components/Header";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className={`${styles.index_page} bg_secondary`}>
        <h2>This is ting base next.js template</h2>
      </main>
      <Footer />
    </div>
  );
}
