// MODULES //

// STYLES //
import styles from "../styles/pages/SignUp.module.scss";

// COMPONENTS //
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import Form from "@/src/components/Form";

// PLUGINS //

// IMAGES //
import Square from "@/public/img/icons/square.svg";
import SemiCircle from "@/public/img/icons/semi-circle.svg";
import Triangle from "@/public/img/icons/triangle.svg";
import Donut from "@/public/img/icons/donut.svg";

export default function SignUp() {
  return (
    <div>
      <Head>
        <title>Sign Up</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.signup_page}`}>
        <div className="container">
          <div className={styles.signup_wrap}>
            <div className={styles.signup_box}>
              <h2 className={`${styles.title} text_center`}>Time Track</h2>
              <p className="text_center text_xs">Sign up and get tracking!</p>
              <Form />
              <Link href={"/login"}>
                <p
                  className={`${styles.alternate_login} text_center text_xxs text_400`}
                >
                  Log in to an existing account
                </p>
              </Link>
            </div>
          </div>
        </div>
        <div className={`${styles.square} ${styles.vector}`}>
          <Image src={Square} alt="Square" />
        </div>
        <div className={`${styles.semi_circle} ${styles.vector}`}>
          <Image src={SemiCircle} alt="Square" />
        </div>
        <div className={` ${styles.scale_circle} ${styles.vector}`}></div>
        <div className={`${styles.circle} ${styles.vector}`}></div>
        <div className={`${styles.triangle} ${styles.vector}`}>
          <Image src={Triangle} alt="Square" />
        </div>
        <div className={`${styles.donut} ${styles.vector}`}>
          <Image src={Donut} alt="Square" />
        </div>
      </main>
    </div>
  );
}
