import styles from "../styles/pages/SignUp.module.scss";

//import components
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Sign Up</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.signup_page}`}>
        <div className="container">
          <div className={styles.signup_wrap}>
            <div className={styles.signup_box}>
              <h2 className={`${styles.title} text_center`}>Time Track</h2>
              <p className="text_center">Sign up and get tracking!</p>
              <div className={styles.form_group}>
                <form>
                  <div className={styles.form_box}>
                    <label htmlFor="email">Email</label>
                    <input type="text" name="email" id="email" />
                  </div>
                  <div className={styles.form_box}>
                    <label htmlFor="password">Password</label>
                    <input type="text" name="password" id="password" />
                  </div>
                  <button type="submit" className="btn_primary text_500">
                    Continue to signup
                  </button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
